# Generated by Django 4.2.4 on 2023-08-23 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Marcador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("playerX", models.IntegerField()),
                ("playerO", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Tablero",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("a1", models.IntegerField()),
                ("a2", models.IntegerField()),
                ("a3", models.IntegerField()),
                ("bl", models.IntegerField()),
                ("b2", models.IntegerField()),
                ("b3", models.IntegerField()),
                ("cl", models.IntegerField()),
                ("c2", models.IntegerField()),
                ("c3", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Turn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("turn", models.BooleanField()),
            ],
        ),
    ]
