# Generated by Django 4.2.4 on 2023-08-23 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("miapp", "0002_alter_tablero_a1_alter_tablero_a2_alter_tablero_a3_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tablero",
            old_name="cl",
            new_name="c1",
        ),
    ]
