# Generated by Django 4.2.4 on 2023-08-23 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("miapp", "0003_rename_cl_tablero_c1"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tablero",
            old_name="bl",
            new_name="b1",
        ),
    ]
