# Generated by Django 3.2.20 on 2023-08-25 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0004_rename_bl_tablero_b1'),
    ]

    operations = [
        migrations.AddField(
            model_name='marcador',
            name='num_games',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tablero',
            name='a1',
            field=models.CharField(default=' ', max_length=1),
        ),
        migrations.AlterField(
            model_name='tablero',
            name='a2',
            field=models.CharField(default=' ', max_length=1),
        ),
        migrations.AlterField(
            model_name='tablero',
            name='a3',
            field=models.CharField(default=' ', max_length=1),
        ),
        migrations.AlterField(
            model_name='tablero',
            name='b1',
            field=models.CharField(default=' ', max_length=1),
        ),
        migrations.AlterField(
            model_name='tablero',
            name='b2',
            field=models.CharField(default=' ', max_length=1),
        ),
        migrations.AlterField(
            model_name='tablero',
            name='b3',
            field=models.CharField(default=' ', max_length=1),
        ),
        migrations.AlterField(
            model_name='tablero',
            name='c1',
            field=models.CharField(default=' ', max_length=1),
        ),
        migrations.AlterField(
            model_name='tablero',
            name='c2',
            field=models.CharField(default=' ', max_length=1),
        ),
        migrations.AlterField(
            model_name='tablero',
            name='c3',
            field=models.CharField(default=' ', max_length=1),
        ),
        migrations.AlterField(
            model_name='turn',
            name='turn',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
