# Generated by Django 3.2.20 on 2023-08-25 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0006_auto_20230825_2142'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Turn',
            new_name='Turno',
        ),
        migrations.RenameField(
            model_name='turno',
            old_name='turn',
            new_name='turno',
        ),
    ]
